# Site settings
author: Linh Mai
title: My Journey from Science to Technology Field
header-img: img/home-bg.png
email: linhnp.mai@gmail.com
copyright_name: Linh Mai
description: > # this means to ignore newlines until "baseurl:"
  The Transition of a Chemist to a Data Scientist 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  linhmai19

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
